import Person from './Person'
import Book from './Book'

export const personData: { [key: string]: Person } = {
  jordanPeterson: {
    fullName: 'Jordan B. Peterson',
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/1/1a/Jordan_Peterson_June_2018.jpg',
  },
  elonMusk: {
    fullName: 'Elon Musk',
    avatar: 'https://www.gstatic.com/tv/thumb/persons/487130/487130_v9_ba.jpg',
  },
  iainMcGilchrist: {
    fullName: 'Iain McGilchrist',
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Iain_McGilchrist.png',
  },
  marcusWhybrow: {
    fullName: 'Marcus Whybrow',
    avatar:
      'https://avatars2.githubusercontent.com/u/278456?s=460&u=cc5e038e9b5d73a3498306c58aa96d05ebb7696f&v=4',
  },
}

const { jordanPeterson, elonMusk, iainMcGilchrist, marcusWhybrow } = personData

export const bookData: Book[] = [
  {
    title: 'On the Geneology of Morals',
    author: 'Friedrich Nietzsche',
    link: 'https://smile.amazon.co.uk/dp/B00CPU9NN8',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Will to Power',
    author: 'Friedrich Nietzsche',
    link: 'https://smile.amazon.co.uk/dp/B01J4WF9PU',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Twilight of Idols and Anti-Christ',
    author: 'Friedrich Nietzsche',
    link: 'https://smile.amazon.co.uk/dp/B002RI945U',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Joyous Science',
    author: 'Friedrich Nietzsche',
    link: 'https://smile.amazon.co.uk/dp/B07D1FFF5W',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Charterhouse of Parma',
    author: 'Henri Stendhal',
    link: 'https://smile.amazon.co.uk/dp/0140449663',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Red and the Black',
    author: 'Henri Stendhal',
    link: 'https://smile.amazon.co.uk/dp/0140447644',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Wuthering Heights',
    author: 'Wuthering Heights',
    link: 'https://smile.amazon.co.uk/dp/B002RI97IO',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    link: 'https://smile.amazon.co.uk/dp/B01FIWFE0K',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    link: 'https://smile.amazon.co.uk/dp/1857150961',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Demons',
    author: 'Dostoevsky',
    link: 'https://smile.amazon.co.uk/dp/1857151828',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Idiot',
    author: 'Dostoevsky',
    link: 'https://smile.amazon.co.uk/dp/0375413928',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Karamazov Brothers',
    author: 'Dostoevsky',
    link: 'https://smile.amazon.co.uk/dp/0199536376',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Flowers for Algernon',
    author: 'Daniel Keyes',
    link: 'https://smile.amazon.co.uk/dp/1857989384',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Lord of the Flies',
    author: 'William Golding',
    link: 'https://smile.amazon.co.uk/dp/B007KOHV2Y',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Stone Angel',
    author: 'Margaret Laurence',
    link: 'https://smile.amazon.co.uk/dp/B01CGID56Y',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    link: 'https://smile.amazon.co.uk/dp/B002RI9X8S',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    author: 'Ken Kesey',
    link: 'https://smile.amazon.co.uk/dp/B005IP513I',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'I, Claudius',
    author: 'Robert Graves',
    link: 'https://smile.amazon.co.uk/dp/B002RI9HR0',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Down and Out in Paris and London',
    author: 'George Orwell',
    link: 'https://smile.amazon.co.uk/dp/B002RI9IT2',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Nineteen Eighty-Four',
    author: 'George Orwell',
    link: 'https://smile.amazon.co.uk/dp/1857151348',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Homage to Catalonia',
    author: 'George Orwell',
    link: 'https://smile.amazon.co.uk/dp/B002RI9XHO',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Road to Wigan Pier',
    author: 'George Orwell',
    link: 'https://smile.amazon.co.uk/dp/B002RI9M48',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'East of Eden',
    author: 'John Steinbeck',
    link: 'https://smile.amazon.co.uk/dp/B002RI9K5Y',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A Farewell to Arms',
    author: 'Ernest Hemingway',
    link: 'https://smile.amazon.co.uk/dp/B00FU7VBBA',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'For Whom the Bell Tolls',
    author: 'Ernest Hemingway',
    link: 'https://smile.amazon.co.uk/dp/B00FU7VCQE',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Cancer Ward',
    author: 'Aleksandr Solzhenitsyn',
    link: 'https://smile.amazon.co.uk/dp/B005TKD918',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Gulag Archipelago',
    author: 'Aleksandr Solzhenitsyn',
    link: 'https://smile.amazon.co.uk/dp/B07JCWJ8TC',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The First Circle',
    author: 'Aleksandr Solzhenitsyn',
    link: 'https://smile.amazon.co.uk/dp/B00667J1HE',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Big Sleep',
    author: 'Raymond Chandler',
    link: 'https://smile.amazon.co.uk/dp/0241956285',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Long Good-bye',
    author: 'Raymond Chandler',
    link: 'https://smile.amazon.co.uk/dp/B002RI9FU4',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Maltese Falcon',
    author: 'Dashiell Hammett',
    link: 'https://smile.amazon.co.uk/dp/B00N20V112',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Island',
    author: 'Aldous Huxley',
    link: 'https://smile.amazon.co.uk/dp/B0031RS72C',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Point Counter Point',
    author: 'Aldous Huxley',
    link: 'https://smile.amazon.co.uk/dp/B0031RSBTQ',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Fratricides',
    author: 'Nikos Kazantzakis',
    link: 'https://smile.amazon.co.uk/dp/0571105068',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Zorba the Greek',
    author: 'Nikos Kazantzakis',
    link: 'https://smile.amazon.co.uk/dp/0571241700',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Fear and Loathing in Las Vegas',
    author: 'Hunter S. Tompson',
    link: 'https://smile.amazon.co.uk/dp/B00NKY0TNG',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Sometimes a Great Notion',
    author: 'Ken Kesey',
    link: 'https://smile.amazon.co.uk/dp/0140045295',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Electric Kool Aid Acid Test',
    author: 'Tom Wolfe',
    link: 'https://smile.amazon.co.uk/dp/0552993662',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Horses Mouth',
    author: 'Joyce Carey',
    link: 'https://smile.amazon.co.uk/dp/B01NBOQ7V4',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The House of God',
    author: 'Samuel Shem',
    link: 'https://smile.amazon.co.uk/dp/B0031RSATC',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Master and Margarita',
    author: 'Mikhail Bulgakov',
    link: 'https://smile.amazon.co.uk/dp/B07FM5KQPS',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    link: 'https://smile.amazon.co.uk/dp/B00K1XOV5G',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Tolstoy',
    author: 'Henri Troyat',
    link: 'https://smile.amazon.co.uk/dp/0802137687',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Zen and the Art of Motorcycle Maintenance',
    author: 'Robert M. Pirsig',
    link: 'https://smile.amazon.co.uk/dp/B0063HC7EQ',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A Confession and Other Religious Writings',
    author: 'Leo Tolstoy',
    link: 'https://smile.amazon.co.uk/dp/B002RI9MSO',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Paradise Lost',
    author: 'John Milton',
    link: 'https://smile.amazon.co.uk/dp/B002XHNNGQ',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Explaining Postmodernism',
    author: 'Stephen R.C. Hicks',
    link: 'https://smile.amazon.co.uk/dp/B005D53DG0',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Discovery of the Unconscious',
    author: 'Henri F. Ellenberger',
    link: 'https://smile.amazon.co.uk/dp/0465016731',
    read: 1,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Genius',
    author: 'Hans Eysenck',
    link: 'https://smile.amazon.co.uk/dp/0521485088',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'An Outline of Psychoanalysis',
    author: 'Sigmund Freud',
    link: 'https://smile.amazon.co.uk/dp/B002RI9Y3C',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Interpreting Dreams',
    author: 'Sigmund Freud',
    link: 'https://smile.amazon.co.uk/dp/B002RI98AG',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Answer to Job',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00FDR4T1G',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Modern Man in Search of a Soul',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BGMJO',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Symbols of Transformation',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00QRZE8VY',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Two Essays on Analytical Psychology',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIEWM',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Archetypes and the Collective Unconscious',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIDG4',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Aion',
    subtitle: 'Researches into the Phenomenology of the Self',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIF1W',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Psychology and Religion',
    subtitle: 'West and East',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIE4U',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Psychology and Alchemy',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIDKA',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Mysterium Coniunctionis',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00QRZED3M',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Symbolic Life',
    subtitle: 'Miscellaneous Writings',
    author: 'C.G. Jung',
    link: 'https://smile.amazon.co.uk/dp/B00R6BIDK0',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Existence',
    subtitle: 'A new dimension in psychiatry and psychology',
    author: 'Rollo May, Ernest Angel, and Henri E. Ellenberger',
    link: 'https://smile.amazon.co.uk/dp/1568212712',
    read: 1,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Origins and History of Consciousness',
    author: 'Erich Neumann',
    link: 'https://smile.amazon.co.uk/dp/B019P2PSDM',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Great Mother',
    author: 'Erich Neumann',
    link: 'https://smile.amazon.co.uk/dp/B00RKMZZSI',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Play, Dreams and Imitation in Childhood',
    author: 'Jean Piaget',
    link: 'https://smile.amazon.co.uk/dp/B00DSLYG0S',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Moral Judgment of the Child',
    author: 'Jean Piaget',
    link: 'https://smile.amazon.co.uk/dp/B00GHJEATU',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'On Becoming a Person',
    author: 'Carl R. Rogers',
    link: 'https://smile.amazon.co.uk/dp/B005DKRFLO',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A Way of Being',
    author: 'Carl R. Rogers',
    link: 'https://smile.amazon.co.uk/dp/B00BS03VCU',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Human Cognitive Abilities',
    subtitle: 'A Survey of Factor-Analytic Studies',
    author: 'John B. Carroll',
    link: 'https://smile.amazon.co.uk/dp/0521387124',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Myth of Mental Illness',
    subtitle: 'Foundations of a Theory of Personal Conduct',
    author: 'Thomas S. Szasz',
    link: 'https://smile.amazon.co.uk/dp/B004V54ENO',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Great Escape',
    subtitle: 'Health, Wealth, and the Origins of Inequality',
    author: 'Angus Deaton',
    link: 'https://smile.amazon.co.uk/dp/B00CXTMWKM',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Enlightenment Now',
    subtitle: 'The Case for Reason, Science, Humanism, and Progress',
    author: 'Steven Pinker',
    link: 'https://smile.amazon.co.uk/dp/B075ZGBY6Q',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Rational Optimist',
    subtitle: 'How Prosperity Evolves',
    author: 'Matt Ridley',
    link: 'https://smile.amazon.co.uk/dp/B003ODI67E',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Factfulness',
    subtitle:
      'Ten Reasons We’re Wrong About the World–and Why Things Are Better Than You Think',
    author: 'Hans Rosling',
    link: 'https://smile.amazon.co.uk/dp/B0769XK7D6',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Earth in Human Hands',
    subtitle: "Shaping Our Planet's Future",
    author: 'David Grinspoon',
    link: 'https://smile.amazon.co.uk/dp/1455589128',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Mephistopheles',
    subtitle: 'The Devil in the Modern World',
    author: 'Jeffrey Burton Russell',
    link: 'https://smile.amazon.co.uk/dp/0801497183',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A History of Religious Ideas, Volume 1',
    subtitle: 'From the Stone Age to the Eleusinian Mysteries',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/B00IGQI7OQ',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A History of Religious Ideas, Volume 2',
    subtitle: 'From Gautama Buddha to the Triumph of Christianity',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/B00KMQC2ZI',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'A History of Religious Ideas, Volume 3',
    subtitle: 'From Muhammad to the Age of Reforms',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/B00KLX5J7U',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Myth and Reality',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/B00H7G5IQG',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Myths, Dreams and Mysteries',
    subtitle: 'The Encounter Between Contemporary Faiths and Archaic Realities',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/0061319430',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Shamanism',
    subtitle: 'Archaic Techniques of Ecstasy',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/0691119422',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Forge and the Crucible',
    subtitle: 'The Origins and Structures of Alchemy',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/0226203905',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Sacred and the Profane',
    subtitle: 'The Nature of Religion',
    author: 'Mircea Eliade',
    link: 'https://smile.amazon.co.uk/dp/B00SJ7LTC4',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Great Code',
    subtitle: 'The Bible and Literature',
    author: 'Northrop Frye',
    link: 'https://smile.amazon.co.uk/dp/0156027801',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Words with Power',
    subtitle: 'Being a Second Study of The Bible and Literature',
    author: 'Northrop Frye',
    link: 'https://smile.amazon.co.uk/dp/0156983656',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Crisis of Islam',
    subtitle: 'Holy War and Unholy Terror',
    author: 'Bernard Lewis',
    link: 'https://smile.amazon.co.uk/dp/0753817527',
    read: 0,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The World’s Religions',
    author: 'Huston Smith',
    link: 'https://smile.amazon.co.uk/dp/B004I43MPE',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Bible',
    subtitle:
      'Designed to be Read as Living Literature. The Old and the New Testaments in the King James Version',
    author: 'Ernest Sutherland Bates',
    link: 'https://smile.amazon.co.uk/dp/B010EWIA9Q',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Little Science, Big Science',
    author: 'Derek J. de Solla Price',
    link: 'https://smile.amazon.co.uk/dp/0231085621',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Mystery of Capital',
    subtitle: 'Why Capitalism Triumphs in the West and Fails Everywhere Else',
    author: 'Hernando De Soto',
    link: 'https://smile.amazon.co.uk/dp/B004FV4XTE',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Systems Bible',
    subtitle:
      "The Beginner's Guide to Systems Large and Small, Being the Third Edition of Systemantics",
    author: 'John Gall',
    link: 'https://smile.amazon.co.uk/dp/B00AK1BIDM',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Rise of Statistical Thinking 1820-1900',
    author: 'Theodore M. Porter',
    link: 'https://smile.amazon.co.uk/dp/069102409X',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Stalin',
    subtitle:
      'The First In-depth Biography Based on Explosive New Documents from Russia’s Secret Archives',
    author: 'Edvard Radzinsky',
    link: 'https://smile.amazon.co.uk/dp/0385479549',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Rise and Fall of the Third Reich',
    author: 'William L. Shirer',
    link: 'https://smile.amazon.co.uk/dp/B01IA89O2I',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Shake Hands With The Devil',
    subtitle: 'The Failure of Humanity in Rwanda',
    author: 'Lt. Gen. Romeo Dallaire',
    link: 'https://smile.amazon.co.uk/dp/B0034FJGEY',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Rape Of Nanking',
    subtitle: 'The Forgotten Holocaust Of World War II',
    author: 'Iris Chang',
    link: 'https://smile.amazon.co.uk/dp/B06XC5SBSP',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: "Hitler's Table Talk",
    author: 'Martin Bormann',
    link: 'https://smile.amazon.co.uk/dp/1684186153',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'PANZRAM',
    subtitle: 'A Journal of Murder',
    author: 'Thomas E. Gaddis, James O Long',
    link: 'https://smile.amazon.co.uk/dp/1878923145',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Ecological Approach to Visual Perception',
    author: 'James J. Gibson',
    link: 'https://smile.amazon.co.uk/dp/B00PWAKE2M',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The New Executive Brain',
    subtitle: 'Frontal Lobes in a Complex World',
    author: 'Elkhonon Goldberg',
    link: 'https://smile.amazon.co.uk/dp/B003D5DK0G',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Neuropsychology of Anxiety',
    subtitle: 'Second Edition',
    author: 'Jeffrey A. Gray, and Neil McNaughton',
    link: 'https://smile.amazon.co.uk/dp/0198522711',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Emotional Brain',
    author: 'Joseph LeDoux',
    link: 'https://smile.amazon.co.uk/dp/0753806703',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Affective Neuroscience',
    subtitle: 'The Foundations of Human and Animal Emotions',
    author: 'Jaak Panksepp',
    link: 'https://smile.amazon.co.uk/dp/B00590X4HM',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Awakenings',
    author: 'Oliver Sacks',
    link: 'https://smile.amazon.co.uk/dp/B00569FP8M',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'An Anthropologist on Mars',
    author: 'Oliver Sacks',
    link: 'https://smile.amazon.co.uk/dp/B00569FOT2',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Brain Architecture',
    subtitle: 'Understanding the Basic Plan',
    author: 'Larry W. Swanson',
    link: 'https://smile.amazon.co.uk/dp/019537858X',
    read: 0,
    own: 0,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Zero to One',
    subtitle: 'Notes on Startups, or How to Build the Future',
    author: 'Peter Thiel, with Blake Masters',
    link: 'https://smile.amazon.co.uk/dp/B00KHX0II4',
    read: 0,
    own: 0,
    recommenders: [elonMusk],
  },
  {
    title: 'Einstein',
    subtitle: 'His Life and Universe',
    author: 'Walter Isaacson',
    link: 'https://smile.amazon.co.uk/dp/B002RI9NQU',
    read: 0,
    own: 0,
    recommenders: [elonMusk],
  },
  {
    title: 'Benjamin Franklin',
    subtitle: 'An American Life',
    author: 'Walter Isaacson',
    link: 'https://smile.amazon.co.uk/dp/B003YFJ3ZQ',
    read: 0,
    own: 0,
    recommenders: [elonMusk],
  },
  {
    title: 'Structures',
    subtitle: "Or Why Things Don't Fall Down",
    author: 'J.E. Gordon',
    link: 'https://smile.amazon.co.uk/dp/B002XHNNHU',
    read: 0,
    own: 0,
    recommenders: [elonMusk],
  },
  {
    title: 'How to Spend $75 Billion to Make the World a Better Place',
    author: 'Bjørn Lomborg',
    link: 'https://smile.amazon.co.uk/dp/B00DGY4D78',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Progress',
    subtitle: 'Ten Reasons to Look Forward to The Future',
    author: 'Johan Norberg',
    link: 'https://smile.amazon.co.uk/dp/B07ZWGL32W',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'The Man Who Mistook His Wife For A Hat',
    author: 'Oliver Sachs',
    link: 'https://smile.amazon.co.uk/dp/B00M4406DQ',
    read: 1,
    own: 1,
    recommenders: [jordanPeterson],
  },
  {
    title: 'Tao: The Watercourse Way',
    author: 'Alan Watts',
    link: 'https://smile.amazon.co.uk/dp/1788164466',
    read: 0,
    own: 0,
    recommenders: [iainMcGilchrist],
  },
  {
    title: 'The God of the Left Hemisphere',
    author: 'Roderick Tweedy',
    link: 'https://smile.amazon.co.uk/dp/1780491018',
    read: 0,
    own: 0,
    recommenders: [iainMcGilchrist],
  },
  {
    title: 'Key Writings',
    author: 'Henri Bergson',
    link: 'https://smile.amazon.co.uk/dp/1472528018',
    read: 0,
    own: 0,
    recommenders: [iainMcGilchrist],
  },
  {
    title: 'The Principles of Psychology',
    author: 'William James',
    link: 'https://smile.amazon.co.uk/dp/1543183182',
    read: 0,
    own: 0,
    recommenders: [iainMcGilchrist],
  },
  {
    title: 'The Magic of Handwriting',
    author: 'Pedro Corrêa do Lago',
    link:
      'https://www.taschen.com/pages/en/catalogue/classics/all/07701/facts.the_magic_of_handwriting_the_correa_do_lago_collection.htm',
    read: 0,
    own: 0,
    recommenders: [marcusWhybrow],
  },
]
